### ISSUE TITLE
CKEditor update

### ISSUE THREAD

**Issue by rhulshof** [PaulNieuwelaar/htmleditor#1]
Hi Paul! What a great solution you built! Would it be possible to update this solution with a more recent version of CKeditor? Unfortunately the used version of CKeditor uses a really old version of jQuery, etc. which does not pass recent security (PEN) tests at our organization.

**Comment by PaulNieuwelaar** [comment]
Hi, I've just updated the CKEditor version and JQuery version to the latest and republished as v1.2. Let me know if there are any issues. Paul
